version: "3.9"

services:
  db:
    image: postgres:13.2
    container_name: postgres_compose
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8090:5432"
    volumes:
      - ./postgres-db-volumes:/var/lib/postgres/data

  app:
    build:
      context: service
      dockerfile: Dockerfile
    container_name: fastapi_compose
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-include *
    restart: always
    environment:
      DB_CONN: ${DB_CONN}
    ports:
      - "8000:8000"
    volumes:
      - ./service:/app
    depends_on:
      - db
